meta:
  engine: 4.1.0
  author: Nevimmu
units:
  kx: cx
  ky: cy
  pad: 4
  
  px: kx + pad
  py: ky + pad

  extra: 1.5px
  nicewidh: 17.78

  drill_size: 4
  drill_outline: .3

points:
  zones:
    matrix:
      # Fix placement on KiCAD sheet.
      anchor:
        shift: [90, -130]
      key:
        spread: kx
        padding: ky
      rows:
        mod:
          row_net: P4
        bottom:
          row_net: P5
        home:
          row_net: P6
        top:
          row_net: P7
        number:
          row_net: P8
      columns:
        outer:
          key:
            column_net: P21
        pinky:
          key:
            column_net: P20
        ring:
          key:
            column_net: P19
        middle:
          key:
            column_net: P18
        index:
          key:
            column_net: P15
        inner:
          key:
            column_net: P14
outlines:
  keys:
    - what: rectangle
      where: true
      size: [14, 14]

  board:
    - what: polygon
      operation: stack
      points:
        - ref: matrix_outer_number
          shift: [-0.5px,0.5py]
        - ref: matrix_inner_number
          shift: [extra, 0.5py]
        - ref: matrix_inner_mod
          shift: [extra, -0.5py]
        - ref: matrix_outer_mod
          shift: [-0.5px, -0.5py]
      fillet: 2

  combo:
    - name: board
    - operation: subtract
      name: keys

  top:
    - what: polygon
      operation: stack
      points:
        - ref: matrix_outer_number
          shift: [-0.5px,0.5py]
        - ref: matrix_inner_number
          shift: [0.5px, 0.5py]
        - ref: matrix_inner_mod
          shift: [0.5px, -0.5py]
        - ref: matrix_outer_mod
          shift: [-0.5px, -0.5py]
      fillet: 2

  combo_top:
    - name: top
    - operation: subtract
      name: keys
  
pcbs:
  limule_topplate:
    outlines:
      main:
        template: kicad8
        outline: combo_top

    footprints:
      holeTopLeft:
        what: infused-kim/mounting_hole
        where:
          ref: matrix_outer_number
          shift: [0.5kx,-0.5ky]

      holeBottomLeft:
        what: infused-kim/mounting_hole
        where:
          ref: matrix_outer_mod
          shift: [0.5kx,0.5ky]

      holeTopRight:
        what: infused-kim/mounting_hole
        where:
          ref: matrix_inner_number
          shift: [-0.5kx,-0.5ky]

      holeBottomRight:
        what: infused-kim/mounting_hole
        where:
          ref: matrix_inner_mod
          shift: [-0.5kx,0.5ky]

      holeMiddle:
        what: infused-kim/mounting_hole
        where:
          ref: matrix_ring_bottom
          shift: [0.5kx,0.5ky]

  limule_pcb:
    outlines:
      main:
        template: kicad8
        outline: board

    footprints:
      choc_hotswap:
        what: infused-kim/choc
        where: true
        params:
          reverse: true
          hotswap: true
          from: "{{column_net}}"
          to: "{{colrow}}"

      diode: 
        what: infused-kim/diode
        where: true
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
          include_tht: false
        adjust:
          shift: [0.4kx, -0.20ky]
          rotate: 90

      nicenano: 
        what: infused-kim/nice_nano_pretty
        where:
          ref: matrix_inner_number
          shift: [21.5, -6]

      niceview:
        what: infused-kim/nice_view
        params:
          side: "F"
          reverse: true
          MOSI: P3
          SCK: P2
          CS: P1
        where:
          ref: matrix_inner_number
          shift: [21.5, -10.5]

      reset:
        what: infused-kim/switch_reset
        params:
          reverse: true
        where:
          ref: matrix_inner_bottom
          shift: [31.3, 0]

      power:
        what: infused-kim/switch_power
        params:
          reverse: true
        where:
          ref: matrix_inner_bottom
          shift: [31.3, 10]

      jst:
        what: ceoloide/battery_connector_jst_ph_2 #jstph
        params:
          reversible: true
        where:
          ref: matrix_inner_home
          shift: [23, -5]
          rotate: -90

      front_text: &text
        what: text
        where: &textWhere
          ref: matrix_inner_bottom
          shift: [18, -7]
        params: &textParams
          text: Limule - v1
          justify: left

      back_text:
        <<: *text
        where:
          <<: *textWhere
          shift: [23, -7]
        params:
          <<: *textParams
          layer: B.SilkS
          justify: left mirror

      holeTopLeft:
        what: infused-kim/mounting_hole
        where:
          ref: matrix_outer_number
          shift: [0.5kx,-0.5ky]
        params:
          drill: drill_size
          outline: drill_outline

      holeBottomLeft:
        what: infused-kim/mounting_hole
        where:
          ref: matrix_outer_mod
          shift: [0.5kx,0.5ky]
        params:
          drill: drill_size
          outline: drill_outline

      holeTopRight:
        what: infused-kim/mounting_hole
        where:
          ref: matrix_inner_number
          shift: [-0.5kx,-0.5ky]
        params:
          drill: drill_size
          outline: drill_outline

      holeBottomRight:
        what: infused-kim/mounting_hole
        where:
          ref: matrix_inner_mod
          shift: [-0.5kx,0.5ky]
        params:
          drill: drill_size
          outline: drill_outline

      holeMiddle:
        what: infused-kim/mounting_hole
        where:
          ref: matrix_ring_bottom
          shift: [0.5kx,0.5ky]
        params:
          drill: drill_size
          outline: drill_outline

      holeCoverBottomLeft:
        what: infused-kim/mounting_hole
        where:
          ref: matrix_inner_mod
          shift: [0.7kx,-0.4ky]

      holeCoverBottomRight:
        what: infused-kim/mounting_hole
        where:
          ref: matrix_inner_mod
          shift: [extra - 0.15kx,-0.4ky]

      holeCoverTopLeft:
        what: infused-kim/mounting_hole
        where:
          ref: matrix_inner_home
          shift: [0.7kx,0.1ky]

      holeCoverTopRight:
        what: infused-kim/mounting_hole
        where:
          ref: matrix_inner_home
          shift: [extra - 0.15kx,0.1ky]

      limule:
        what: limule
        where:
          ref: matrix_outer_number
          shift: [-20, 30]
        params:
          scale: .1

      routes_key:
        what: ceoloide/utility_router
        where: true
        params:
          locked: false
          routes:
            - "B(8.275,-3.75)(8.275,0.675)(7.2,1.75)"  # net: outer_top
            - "F(6.8595,2.0905)(-6.6595,2.0905)(-8.25,0.5)(-8.25,-3.725)"  # net: outer_top
            - "B(-3.275,-5.95)(-1.125,-3.8)(0,-3.8)V(1.125,-3.8)(3.275,-5.95)"  # net: P21

      diode_via:
        what: ceoloide/utility_router
        where: true
        params:
          locked: false
          routes:
            - "(7.2,5.05)V"  # net: P8
            - "(7.2,1.75)V"  # net: outer_number

      routes_col:
        what: ceoloide/utility_router
        where: -/inner/
        params:
          locked: false
          routes:
            - "F(7.2,5.05)(25.2,5.05)"  # net: P8

      routes_row:
        what: ceoloide/utility_router
        where: -/mod/
        params:
          locked: false
          routes:
            - "B(-3.275,-5.95)(-3.124,-5.799)(-3.124,10.899)(-3.275,11.05)"  # net: {{column_net}}