meta:
  engine: 4.1.0
  author: Nevimmu
units:
  kx: cx
  ky: cy
  pad: 4
  
  px: kx + pad
  py: ky + pad

  extra: 1.5px
  nicewidh: 17.78
points:
  zones:
    matrix:
      # Fix placement on KiCAD sheet.
      anchor:
        shift: [90, -130]
      key:
        spread: kx
        padding: ky
      rows:
        mod:
          row_net: P4
        bottom:
          row_net: P5
        home:
          row_net: P6
        top:
          row_net: P7
        number:
          row_net: P8
      columns:
        outer:
          key:
            column_net: P21
        pinky:
          key:
            column_net: P20
        ring:
          key:
            column_net: P19
        middle:
          key:
            column_net: P18
        index:
          key:
            column_net: P15
        inner:
          key:
            column_net: P14
outlines:
  raw:
    - what: rectangle
      where: true
      size: [px, py]
  keys:
    - what: rectangle
      where: true
      size: [kx-0.5,ky-0.5]
  board:
    - what: polygon
      operation: stack
      points:
        - ref: matrix_outer_number
          shift: [-0.5px,0.5py]
        - ref: matrix_inner_number
          shift: [extra, 0.5py]
        - ref: matrix_inner_mod
          shift: [extra, -0.5py]
        - ref: matrix_outer_mod
          shift: [-0.5px, -0.5py]
      fillet: 2

  combo:
    - name: board
    - operation: subtract
      name: keys
pcbs:
  limule:
    outlines:
      main:
        template: kicad8
        outline: board
    footprints:
      choc_hotswap:
        what: infused-kim/choc
        where: true
        params:
          reverse: true
          hotswap: true
          from: "{{column_net}}"
          to: "{{colrow}}"
      diode: 
        what: infused-kim/diode
        where: true
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
          include_tht: false
        adjust:
          shift: [0.4kx, -0.20ky]
          rotate: 90
      nicenano: 
        what: infused-kim/nice_nano_pretty
        where:
          ref: matrix_inner_number
          shift: [21.5, -6]
      niceview:
        what: infused-kim/nice_view
        params:
          side: "F"
          reverse: true
          MOSI: P3
          SCK: P2
          CS: P1
        where:
          ref: matrix_inner_number
          shift: [21.5, -10.5]
      reset:
        what: infused-kim/switch_reset
        params:
          reverse: true
        where:
          ref: matrix_inner_bottom
          shift: [31.3, 0]
      power:
        what: infused-kim/switch_power
        params:
          reverse: true
        where:
          ref: matrix_inner_bottom
          shift: [31.5, 10]
      jst:
        what: ceoloide/battery_connector_jst_ph_2 #jstph
        params:
          reversible: true
        where:
          ref: matrix_inner_home
          shift: [23, -5]
          rotate: -90
      front_text: &text
        what: text
        where: &textWhere
          ref: matrix_inner_bottom
          shift: [18, -7]
        params: &textParams
          text: Limule - v1
          justify: left
      back_text:
        <<: *text
        where:
          <<: *textWhere
          shift: [23, -7]
        params:
          <<: *textParams
          layer: B.SilkS
          justify: left mirror
      holeTopLeft:
        what: infused-kim/mounting_hole
        where:
          ref: matrix_outer_number
          shift: [0.5kx,-0.5ky]
      holeBottomLeft:
        what: infused-kim/mounting_hole
        where:
          ref: matrix_outer_mod
          shift: [0.5kx,0.5ky]
      holeTopRight:
        what: infused-kim/mounting_hole
        where:
          ref: matrix_inner_number
          shift: [-0.5kx,-0.5ky]
      holeBottomRight:
        what: infused-kim/mounting_hole
        where:
          ref: matrix_inner_mod
          shift: [-0.5kx,0.5ky]
      holeMiddle:
        what: infused-kim/mounting_hole
        where:
          ref: matrix_ring_bottom
          shift: [0.5kx,0.5ky]
      holeCoverBottomLeft:
        what: infused-kim/mounting_hole
        where:
          ref: matrix_inner_mod
          shift: [0.7kx,-0.4ky]
      holeCoverBottomRight:
        what: infused-kim/mounting_hole
        where:
          ref: matrix_inner_mod
          shift: [extra - 0.15kx,-0.4ky]
      holeCoverTopLeft:
        what: infused-kim/mounting_hole
        where:
          ref: matrix_inner_home
          shift: [0.7kx,0.1ky]
      holeCoverTopRight:
        what: infused-kim/mounting_hole
        where:
          ref: matrix_inner_home
          shift: [extra - 0.15kx,0.1ky]
      limule:
        what: limule
        where:
          ref: matrix_outer_number
          shift: [-20, 30]
        params:
          scale: .1